import type { DictTypeForm, DictTypeQuery } from './types';
import { systemAdminService } from '../../client/runtime';
const service = systemAdminService.resources.dictTypes;
export const listType = (query: DictTypeQuery) => service.list(query);
export const getType = (id: string | number) => service.get(id);
export const addType = (data: DictTypeForm) => service.add(data);
export const updateType = (data: DictTypeForm) => service.update(data);
export const delType = (ids: string | number | Array<string | number>) => service.delete(ids);
export const refreshCache = () => service.refreshCache();
export const optionselect = () => service.options();
